#!/usr/bin/python3

#Parts:
# Copyright 2015 gRPC authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Runs protoc with the gRPC plugin to generate messages and gRPC stubs."""



# Needs python3-grpc-tools at the same version as the current bundled grpc (or close to it)
# You may need to get it from pip (apt install python3-pip; pip3 install -U grpcio-tools)

# Run this any time warp.proto gets updated, this will generate new warp_pb2*.py files.
from grpc_tools import protoc

protoc.main((
    '',
    '-Isrc',
    '--python_out=src',
    '--grpc_python_out=src',
    'warp.proto'
))
