#!/usr/bin/python3
import os
import sys
import subprocess

if os.path.basename(os.getcwd()) != "testing":
    print("Run this in the 'testing' folder.")
    exit(1)

os.environ["PYTHONPATH"] = os.getcwd()
os.environ["GSETTINGS_BACKEND"] = "memory"

sys.path.insert(0, "/usr/libexec/warpinator")

import warpinator
warpinator.main(True) # testmode
